version: "3"
services:
  web:
    build:
      context: .
    container_name: web_app
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: postgres
      DB_HOST: db
    ports:
      - "8001:8000"
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
        - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - .:/app
    ports:
      - "6379:6379"

  celery:
    restart: always
    build:
      context: .
    environment:
      BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    command: celery -A config worker -l info
    volumes:
      - ./config:/config
    depends_on:
      - redis
  flower:
    restart: always
    build:
      context: .
    environment:
      BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    command: celery -A config flower
    volumes:
      - ./config:/config
    ports:
      - "5566:5555"
    depends_on:
      - celery
      - redis
volumes:
  pgdata:


