# Generated by Django 5.0.4 on 2024-05-08 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_hotel_bookinfo_hotelscomment_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('age', models.PositiveIntegerField(null=True)),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='persons',
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='hotels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_info', to='booking_app.hotel'),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='persons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_info', to='booking_app.person'),
        ),
        migrations.AlterField(
            model_name='hotelscomment',
            name='hotels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_comments', to='booking_app.hotel'),
        ),
        migrations.AlterField(
            model_name='hotelscomment',
            name='persons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_comments', to='booking_app.person'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='persons',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='booking_app.person'),
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('detail', models.CharField(max_length=200, null=True)),
                ('persons', models.ManyToManyField(null=True, related_name='hobbies', to='booking_app.person')),
                ('owners', models.ManyToManyField(null=True, related_name='hobbies', to='booking_app.hotelowner')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='owners',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='booking_app.hotelowner'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hotel_owners',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='booking_app.hotelowner'),
        ),
    ]
