# Generated by Django 5.0.4 on 2024-05-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_hotelowner_remove_hotel_persons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='owners',
            field=models.ManyToManyField(related_name='hobbies', to='booking_app.hotelowner'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='persons',
            field=models.ManyToManyField(related_name='hobbies', to='booking_app.person'),
        ),
    ]
