name: Environment
on: workflow_dispatch
env:
  DJANGO_ENV: production
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DJANGO_ENV: job prod
    steps:
      - name: Print Node env build
        run: |
          echo "${{ env.DJANGO_ENV }}"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Print env deploy
        run: |
          echo "${{ env.DJANGO_ENV }}"
